### ISSUE TITLE
To-do's on email microservice

### ISSUE THREAD

**Issue by margoflewelling** [Hifu-devs/hifu-api#34]
- [x] Add more testing 
- [x] Add sad path 
- [x] send response codes and messages
- [x] Work on making email template nicer
