### ISSUE TITLE
DB Migration

### ISSUE THREAD

**Issue by brian-greeson** [Hifu-devs/hifu-api#5]
Tables to Create
- [ ] User
- [ ] Routes
- [ ] Waypoints
- [ ] Contacts

Relationships
- [ ] User has one routes
- [ ] Route has many waypoints
- [ ] User has one contact
