### ISSUE TITLE
Twilio Research

### ISSUE THREAD

**Issue by brian-greeson** [Hifu-devs/hifu-api#7]
- [ ] Determine SMS requirements
- [ ] Determine Email requirements
- [ ] Figure out request encryption (https)

**Comment by kristastadler** [comment]
Twilio SMS Ruby Quickstart Guide: https://www.twilio.com/docs/sms/quickstart/ruby

**Comment by kristastadler** [comment]
Twilio Sendgrid API Docs for sending email: https://github.com/sendgrid/sendgrid-ruby

**Comment by kristastadler** [comment]
Twilio's SMS service looks really nice -- however, looks like SMS length is limited to 160 characters or it is broken into segmented messages (maybe not the most user friendly?). Is 160 characters enough to get our message across? Or maybe the gist of it with and let them know we emailed full details to them?

https://www.twilio.com/docs/glossary/what-sms-character-limit

**Comment by margoflewelling** [comment]
160 is VERY small, I just played around with "Hi jill, 
You were listed as an emergency contact for john doe. He has not checked back in from his backpacking trip starting on July 1, the local authorities to...." that is 160 right there. I like the notification that we send them an email idea.
